version: '3'
services:
  docker-mysql:
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
